include classpath("application-prod.conf")

pekko.workflow.cluster-bootstrap.enabled = true
pekko.cluster.seed-nodes = []
pekko.cluster.shutdown-after-unsuccessful-join-seed-nodes = 60s
pekko.cluster.min-nr-of-members = 2
pekko.cluster.roles = ["coordinator", "worker", "api-gateway"]
pekko.remote.artery.canonical.hostname = ${?PEKKO_HOSTNAME}

pekko.discovery.kubernetes-api.pod-label-selector = "app=%s"

pekko.management {
  http {
    hostname = ${POD_IP}
    bind-hostname = "0.0.0.0"
    port = 7626
    bind-port = 7626
  }

  cluster.bootstrap.contact-point-discovery {
    discovery-method = kubernetes-api
    service-name = "pekko-workflow"
    port-name = "management"
    required-contact-point-nr = 2
    stable-margin = 5s
  }
}
