apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bigdata-lab
resources:
  - rbac.yaml
  - headless-service.yaml
  - api-service.yaml
  - statefulset.yaml
  - pod-disruption-budget.yaml
configMapGenerator:
  - name: pekko-workflow-config
    files:
      - application-k8s.conf
generatorOptions:
  disableNameSuffixHash: true
