include classpath("application-prod.conf")

pekko.pekko-sys = "pekko-cdc-single-system"
pekko.workflow.cluster-bootstrap.enabled = true
pekko.workflow.mysql-cdc.enabled = true
pekko.cluster.seed-nodes = []
pekko.cluster.min-nr-of-members = 1
pekko.remote.artery.canonical.hostname = ${?PEKKO_HOSTNAME}

pekko.discovery.kubernetes-api.pod-label-selector = "app=%s"

pekko.management {
  http {
    hostname = ${POD_IP}
    bind-hostname = "0.0.0.0"
    port = 7626
    bind-port = 7626
  }

  cluster.bootstrap.contact-point-discovery {
    discovery-method = kubernetes-api
    service-name = "pekko-cdc-single"
    port-name = "management"
    required-contact-point-nr = 1
    stable-margin = 5s
  }
}
